import Head from 'next/head' ;
import {BsFillMoonStarsFill} from 'react-icons/bs' ;
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube, AiFillFacebook, AiFillGithub} from 'react-icons/ai'

export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Chibi senpai</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="bg-white px-10">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className='text-xl text-black from-transparent font-mono'>DEVELOPEDBYCHIBISENPAI</h1>
            <ul className='flex items-center'>
            <li>
              <BsFillMoonStarsFill className="cursor-pointer text-2xl text-black"/>
            </li>
            <li>
            <a className='bg-black px-4 py-2 rounded-md ml-8 text-white font-mono' href="#">Resume</a>
            </li>

            </ul>
          </nav>
          <div className='text-center p-10 '>
            <h2 className='text-5xl py-2 font-mono'>Chibi Senpai</h2>
            <h3 className='text-2xl py-2 font-mono'>Developer and Creator</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>Student who is trying to expertise on software engineering</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
            <AiFillFacebook/>
            <AiFillGithub/>
          </div>
        </section>
      </main>
  </div>
  );
}
